### ISSUE TITLE
Problem - temporal changes plot

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#109] opened 2017-04-08 01:33 UTC
The next thing I've tried was to do a facet plot. While it works good if I want to plot separate polygons (let's say countries) - it fails for temporal changes. Values are displayed only for the last panel. The same problem is with animations with time changes.

```R
library(tmap)
library(rnaturalearth)
library(sf)
library(tidyverse)

df <- data_frame(name='Australia', `1990`=16.8, `1995`=17.9,
                 `2000`=18.9, `2005`=20.1, `2010`=22.2,
                 `2015`=23.9)

world_sf <- ne_countries(returnclass = 'sf') %>% 
        select(name) %>% 
        filter(name=='Australia') %>% 
        left_join(., df, by = "name") %>% 
        gather(year, pop_mln, `1990`:`2015`)

## temporal plot
tm_shape(world_sf) + 
        tm_polygons("pop_mln") +
        tm_facets(by = "year", nrow=3, ncol=2)

## temporal animation
ani_map <- tm_shape(world_sf) + 
        tm_polygons("pop_mln") +
        tm_facets(by = "year", nrow=1, ncol=1)

animation_tmap(ani_map, filename="ani_map.gif", width=800)
```

![rplot](https://cloud.githubusercontent.com/assets/3457131/24824479/d221e124-1bd9-11e7-8fc7-b96fa908bbdd.png)

**Comment by mtennekes** [comment] 2017-04-08 19:06
Nice approach! The intentional purpose of the "by" argument was as in: `tm_shape(World) + tm_facets(by="continent")` Normally, I would use a shape of one feature and multiple variables, as in the `metro` dataset.

Your example fails because Australia is plot six times on top of each other in each facet, and for each facet, a color is assigned to the corresponding 'version' of Australia and `NA`  for the other versions. That's why only the last 'version' (which is drawn last) gets a color in the last facet. Hope you understand:-) It is similar to this:

    data(World)
    Oceania <- World[World$continent=="Oceania", ]
    tm_shape(Oceania) +
    	tm_polygons("pop_est_dens") +
     	tm_facets(by = "name")

The solution is to drop the non-used units/features (in your case, the versions of Australia other than the ones tat correspond to the facets):

    tm_shape(world_sf) + 
    	tm_polygons("pop_mln") +
    	tm_facets(by = "year", nrow=3, ncol=2, drop.units = TRUE)

The way how to deal with such time series maps is still not very elegant. Like I wrote, I would use variables such as `x1990` to `x2015`, and create custom facet labels, but that's also not ideal. So if anyone knows an elegant way how a user could create such plots, let me know.

**Comment by Nowosad** [comment] 2017-04-09 18:20
Hi @mtennekes - `drop.units = TRUE` is fine. However, I have a related question. Let's say I want to make an animation of population changes in time, where each country is in a separate panel. While I'm able to make a plot of country ~ year, I can't just plot changes (in this examples - two panels in time). 

I think that creation of new variables, such as `x1999` to `x2015` could not be the best solution. Borders of countries change in time, therefore it's possible (in theory) to plot population changes and borders (geometry) changes in the same time. 

I would also suggest to create a new function for animated facets (for example `tm_facet_animation`).  Arguments `nrow=1` and `ncol=1` are rather not intuitive. Moreover, this function could have an implementation of temporal changes in panels (`tm_shape(sf_obj) + tm_polygons('pop') + tm_facets(by='country') + tm_facets_animation(by='year')`.

@mtennekes - thanks for your work, I hope that my ideas will help make `tmap` better.

```R
library(tmap)
library(rnaturalearth)
library(sf)
library(tidyverse)

df <- data_frame(name=c('Australia', 'Austria'),
                 `1990`=c(16.8, 7.7), `1995`=c(17.9, 7.9),
                 `2000`=c(18.9, 8.0), `2005`=c(20.1, 8.2),
                 `2010`=c(22.2, 8.4), `2015`=c(23.9, 8.7))

world_sf <- ne_countries(returnclass = 'sf') %>% 
        select(name) %>% 
        filter(name %in% c('Australia', 'Austria')) %>% 
        left_join(., df, by = "name") %>% 
        gather(year, pop_mln, `1990`:`2015`)

## separate countries plot - works
tm_shape(world_sf) + 
        tm_polygons("pop_mln") +
        tm_facets(by = "name", nrow=3, ncol=2, free.coords = TRUE)

## separate countries temporal plot - works
tm_shape(world_sf) + 
        tm_polygons("pop_mln") +
        tm_facets(by = c("name", "year"), free.coords = TRUE)

## separate countries temporal animation - fails
anim <- tm_shape(world_sf) + 
        tm_polygons("pop_mln") +
        tm_facets(by = c("name", "year"), free.coords = TRUE)

animation_tmap(anim, filename = "anim.gif")
```

**Comment by mtennekes** [comment] 2017-04-11 20:06
Thanks for your feedback!

I agree that `ncol=1` and `nrow=1` is not very intuitive for animation. What happens when ncol and nrow are set such that ` ncol * nrow` is smaller than the number of facets, is that a series of plots are generated. With `animation_tmap` these are captured as an animation (rather than multiple plots in the graphics device). Your suggested `tm_facets_animation(by="year")` is actually similar to saying: create a new plot for each year. In that sense, it could also be implemented as a parameter of `tm_facets`:

    tm_shape(sf_obj) + 
      tm_polygons('pop') + 
      tm_facets(by='country', next=`year`).

This probably will also work when the geometry changes over time. In that case, you could use a spatial object where each feature represents one year (like your trick above, with `drop.units = TRUE`)

**Comment by Nowosad** [comment] 2017-04-11 23:47
@mtennekes Yes, you're right - it's a new plot for each year. I like your idea with a new parameter. Its name should be somewhat different - `next` is one of the [reserved words](https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Reserved-words). What do you think about `along`?

Btw - this new parameter (of course if you want that) could also forced `ncol=1` and `nrow=1`, for example:

```R
## temporal animation
ani_map <- tm_shape(world_sf) + 
        tm_polygons("pop_mln") +
        tm_facets(along = "year")

animation_tmap(ani_map, filename="ani_map.gif", width=800)
```

**Comment by Robinlovelace** [comment] 2017-04-12 10:14
Just to say: looks like great progress towards a fix - many thanks for being so responsive Martijn as it feeds directly into our work.

**Comment by mtennekes** [comment] 2017-04-29 09:19
The `along` argument is working now! I also created the `main.title` to `tm_layout`, which serves both the along faceting, as well as regular small multiples (see https://github.com/mtennekes/tmap/issues/105)

In your example:

    tm_shape(world_sf) + 
      tm_polygons("pop_mln") +
      tm_facets(along = "year", drop.units = TRUE)

If you find any bugs or unexpected behaviour, please let me know (and reopen this issue).

**Closed by mtennekes** 2017-04-29 09:19 UTC

**Comment by Nowosad** [comment] 2017-04-29 16:48
Awesome! I'll let you know if I find any bug. 
And once again - thank you for your great work @mtennekes !
