### ISSUE TITLE
title not shown in tmap_mode view 

### ISSUE THREAD

**Issue by Kanoet** [mtennekes/tmap#532] opened 2020-12-08 07:52 UTC
This code worked for me on my old laptop but after updating and installing tmap from cran the title ist not shown in view mode. 

```
cat("\014")
rm(list=ls(all=TRUE)) 

library(tmap)

data("World")

tmap_mode("view")

# does not work in interactive mode 
tm_shape(World)+tm_polygons()+
  tm_layout(title = "Test")


# works in plot mode 
tmap_mode("plot")

tm_shape(World)+tm_polygons()+
  tm_layout(title = "Test")
```

**Comment by francisbarton** [comment] 2021-01-21 14:58
Duplicate of #524 ?

**Closed** 2021-01-21 15:18 UTC
Labels: question
