### ISSUE TITLE
tm_graticules() has problems with projected data 

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#423] opened 2020-04-22 15:19 UTC
``` r
library(tmap)
library(spData)
library(sf)

world2 = st_transform(world, "+proj=moll")

# fails -------------------------------------------------------------------
tm_shape(world2) +
  tm_polygons() +
  tm_graticules()
#> Error in coords[1, ]: subscript out of bounds
```

``` r

# works -------------------------------------------------------------------
g = st_graticule(world2)
tm_shape(g) +
  tm_lines(col = "grey") +
  tm_shape(world2) +
  tm_polygons()
```

![](https://i.imgur.com/lmDghqk.png)

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment] 2020-04-24 10:41
The problem is that  `sf::st_transform(sf::st_as_sfc(st_bbox(world2)), 4326)` returns an empty polygon. I've checked other world projections, and for some it works and for some it doesn't. I might be that proj has become stricter. 

Very frustrating, because it took much time to implement projected grid lines. It's way more complex that you might think, since it automatically determines which grid lines to plot, which labels to plot and at what position.

Probably, I'll have to downgrade tmap. From a user perspective, there is no need to project grid lines in any other CRS than 4326. So, a user would either use `tm_grid` which draws grid lines in the original CRS, or `tm_graticules` which draws graticules (i.e. grid lines in 4326).

**Comment by tim-salabim** [comment] 2020-04-24 11:12
There seems to be a similar issue here
https://github.com/r-spatial/sf/issues/1361

**Comment by Nowosad** [comment] 2020-05-01 18:35
> The problem is that `sf::st_transform(sf::st_as_sfc(st_bbox(world2)), 4326)` returns an empty polygon. I've checked other world projections, and for some it works and for some it doesn't. I might be that proj has become stricter.


@mtennekes I do not know if it helps in anything, but it is possible to get the bounding box with a slightly modified code:

``` r
library(tmap)
library(spData)
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0

world2 = st_transform(world, "+proj=moll")

sf::st_as_sfc(st_bbox(sf::st_transform(world2, 4326)))
#> Geometry set for 1 feature 
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: -180 ymin: -90 xmax: 180 ymax: 83.64513
#> CRS:            EPSG:4326
#> POLYGON ((-180 -90, 180 -90, 180 83.64513, -180...
```

<sup>Created on 2020-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment] 2020-06-10 10:42
Thanks for the tip @tim-salabim but this has already been fixed with the recent commits:-)

**Closed by mtennekes** 2020-06-10 10:42 UTC
Labels: bug
