### ISSUE TITLE
Combine multiple polygon layers in one interactive map

### ISSUE THREAD

**Issue by evandermeijde** [mtennekes/tmap#175] opened 2018-02-21 15:35 UTC
I first posed this question on stackoverflow [here](https://stackoverflow.com/questions/48906791/combine-multiple-polygon-layers-in-one-interactive-map-r-tmap-package).

I am trying to draw one single interactive map in R using the tmap package.

I have one polygon shape with data from various years. When I use tm_shape() + tm_fill() for each year it automatically makes a new, separate map for each year.

I would like to plot multiple layers in one interactive map. This way, by selecting different layers in the drop down menu on the left, you can see the change over the years.

Thanks for the package btw, we use it a lot!

This is my script:

```{r}
require(rgdal)
require(tidyverse)
require(tmap)

# files
download.file("https://www.haarlem.nl/bestandsopslag/bestanden/Opendata/Veiligheid_-_Misdrijven.csv", "veiligheid_misdrijven_haarlem.csv")
download.file("https://www.cbs.nl/-/media/_pdf/2016/35/shape%202014%20versie%2030.zip", "buurten.zip")
unzip("buurten.zip")

# read shape (Haarlem)
shape <- readOGR("uitvoer_shape",layer=ogrListLayers("uitvoer_shape")[1])[4546:4585,]
# change projection
shape <- spTransform(shape, CRS("+proj=sterea +lat_0=52.15616055555555 
                                +lon_0=5.38763888888889 +k=0.999908 
                                +x_0=155000 +y_0=463000 +ellps=bessel 
                                +units=m +towgs84=565.2369,50.0087,
                                465.658,-0.406857330322398,0.350732676542563,
                                -1.8703473836068,4.0812 +no_defs"))
# read data
data <- as.tibble(read.table("veiligheid_misdrijven_haarlem.csv", 
                         header=TRUE, sep=";", dec=",",
                         skip = 4, nrows = 40, stringsAsFactors = FALSE))
# clean data
data <- data %>%
   separate(X, into = c("buurt", "nummer", "name"), sep = c(6,10)) %>%
   select(-buurt, -nummer) %>%
   arrange(name)

# bind data to shape
shape@data <- cbind(arrange(shape@data,BU_NAAM), data)

# plot interactive map
tmap_mode("view")
tm_shape(shape) +
  tm_borders(alpha=0.5) +
  tm_fill(c("X2000","X2013"), style="quantile", alpha=.5, 
          palette=colorRampPalette(c("white", "red"))(5), 
          popup.vars = c("name","X2000","X2013") ) + 
tm_scale_bar()
```

**Comment by mtennekes** [comment] 2018-02-23 10:31
Thanks for your question, Elisabeth! I've had this question before, and it does make sense to show the maps as layers rather than facets in view mode. Therefore, I'll leave this issue open.

A short term solution is to split the `tm_fill` into two groups:

```r
tm_shape(shape) +
  tm_borders(alpha=0.5) +
  tm_fill("X2000", breaks = breaks, alpha=.5, 
          palette=colorRampPalette(c("white", "red"))(5), 
          popup.vars = c("name","X2000","X2013") ) + 
tm_shape(shape) +
  tm_borders(alpha=0.5) +
  tm_fill("X2013", breaks = breaks, alpha=.5, 
          palette=colorRampPalette(c("white", "red"))(5), 
          popup.vars = c("name","X2000","X2013") ) + 
tm_scale_bar()
```

In this solution, you'll have to define the breaks manually to make sure they are consistent across both layers.

**Comment by mtennekes** [comment] 2018-04-22 20:26
I've added the argument `as.layers` to `tm_facets`, which converts small multiples to (overlay) layers.

Some examples:

```{r}
data(World)
tmap_mode("view")

tm_shape(World) +
	tm_polygons("HPI") +
	tm_facets(by = "continent", as.layers = TRUE)


tm_shape(World) +
	tm_polygons(c("well_being", "life_exp"),
				style=c("pretty", "fixed"), breaks=list(NULL, c(65,70,75,80,85)),
				palette=list("Oranges", "Purples"),
				border.col = "black",
				title=c("Well-Being Index", "Life Expectancy")) +
	tm_format("World") + tm_facets(as.layers = TRUE)
```

Due to limitations of leaflet, it is not possible (at least, not easy) to:
* Select these layers with a radio button (which would make more sense). So they have to be selected with independent check boxes. 
* Hide the legend when deselecting the corresponding layer.

Hope it's working well. If not, please let me know.

**Comment by tim-salabim** [comment] 2018-04-22 21:09
@mtennekes laflet now allows a group argument to be passed to `addLegend` so that the legends get bound to the layer.

```r
library(leaflet)

# example taken from ?leaflet::addLegend
df <- local({
  n <- 300; x <- rnorm(n); y <- rnorm(n)
  z <- sqrt(x ^ 2 + y ^ 2); z[sample(n, 10)] <- NA
  data.frame(x, y, z)
})
pal <- colorNumeric("OrRd", df$z)
leaflet(df) %>%
  addTiles() %>%
  addCircleMarkers(~x, ~y, color = ~pal(z), group = "circles") %>%
  addLegend(pal = pal, values = ~z, group = "circles", position = "bottomleft") %>%
  addLayersControl(overlayGroups = c("circles"))
```

**Comment by mtennekes** [comment] 2018-04-23 12:40
Thanks Tim for the tip! I was hoping for this feature, and nowadays it's quicker to post this issue on github than to find out yourself:-)

I'll close this issue for now. If anything does not work as expected, please feel free to reopen it.

**Closed by mtennekes** 2018-04-23 12:40 UTC
Labels: enhancement

**Comment by bobolearythebadger** [comment] 2019-05-09 20:38
This seems to work well if we have all the data of interest in the form of tm_polygons("data1", "data2", ect) however when their are two polygons i.e.  tm_shape(df) + tm_polygons("data1) + tm_shape(df2) + tm_polygons("data2") the addition of tm_facets(as.layers = TRUE) ends up with an "Error in mapply(function(gpl, indices, dt) { : zero-length inputs cannot be mixed with those of non-zero length"

**Comment by mtennekes** [comment] 2019-05-10 08:58
@bobolearythebadger It should be working now. If not, please reopen this issue and provide a reproducible example.

**Comment by bobolearythebadger** [comment] 2019-05-10 13:38
my_map <- tm_shape(Corn) + 
  tm_polygons("Percent Corn Planted 2019",
              popup.vars = c("Percent Corn Planted 2019"= "Percent Corn Planted 2019",
                         "Percent Corn Planted 2018"= "Percent Corn Planted 2018",
                         "5 Year Average" = "5 Year Average"),
              popup.format = list(),
              id = "State") + 
  tm_text("Comparison", size = 1.25) +
  tm_shape(Soybeans) +
  tm_polygons("Percent Soybean Planted 2019", 
              id = "State",
              popup.vars = c("Percent Soybean Planted 2019"= "Percent Soybean Planted 2019",
                         "Percent Soybean Planted 2018"= "Percent Soybean Planted 2018",
                         "5 Year Soybean Average" = "5 Year Soybean Average"))+
  tm_text("Comparison", size = 1.25) + 
  tmap_style("cobalt")+
  tm_facets(as.layers = TRUE) 

my_map <- tmap_leaflet(my_map) 
Error in mapply(function(gpl, indices, dt) { : 
  zero-length inputs cannot be mixed with those of non-zero length

**Comment by mtennekes** [comment] 2019-05-10 14:28
Thanks for the example. Could you make it reproducible, i.e. either share `Corn` and Soybeans` (e.g. by email) or use other spatial objects?

**Comment by mtennekes** [comment] 2019-05-12 07:23
`as.layers` is/should only be applicable when there actually are facets. In your example, there are no layers, just 2 layers of polygons. In interactive mode, these are already shown as layers.

You can see the effect of `as.layers` in your example as follows:

```r
my_map <- tm_shape(Corn) +
	tm_polygons(c("Percent Corn Planted 2018", "Percent Corn Planted 2019"),
				popup.vars = c("Percent Corn Planted 2019"= "Percent Corn Planted 2019",
							   "Percent Corn Planted 2018"= "Percent Corn Planted 2018",
							   "5 Year Average" = "5 Year Average"),
				popup.format = list(),
				id = "State") +
	tm_text("Comparison", size = 1.25) +
	tm_shape(Soybeans) +
	tm_polygons(c("Percent Soybean Planted 2018", "Percent Soybean Planted 2019"),
				id = "State",
				popup.vars = c("Percent Soybean Planted 2019"= "Percent Soybean Planted 2019",
							   "Percent Soybean Planted 2018"= "Percent Soybean Planted 2018",
							   "5 Year Soybean Average" = "5 Year Soybean Average"))+
	tm_text("Comparison", size = 1.25) +
	tm_style("cobalt") +
	tm_facets(as.layers = TRUE)
```

The error was caused by the 'missuse' of as.facets. I fixed it with an extra check.
